# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/FPGA/Ultra96_V2_constraints_190430.xdc

# Block Designs: bd/block_design/block_design.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==block_design || ORIG_REF_NAME==block_design} -quiet] -quiet

# IP: bd/block_design/ip/block_design_zynq_ultra_ps_e_0_2/block_design_zynq_ultra_ps_e_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==block_design_zynq_ultra_ps_e_0_2 || ORIG_REF_NAME==block_design_zynq_ultra_ps_e_0_2} -quiet] -quiet

# IP: bd/block_design/ip/block_design_xbar_0/block_design_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==block_design_xbar_0 || ORIG_REF_NAME==block_design_xbar_0} -quiet] -quiet

# IP: bd/block_design/ip/block_design_ps8_0_axi_periph_3/block_design_ps8_0_axi_periph_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==block_design_ps8_0_axi_periph_3 || ORIG_REF_NAME==block_design_ps8_0_axi_periph_3} -quiet] -quiet

# IP: bd/block_design/ip/block_design_rst_ps8_0_100M_3/block_design_rst_ps8_0_100M_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==block_design_rst_ps8_0_100M_3 || ORIG_REF_NAME==block_design_rst_ps8_0_100M_3} -quiet] -quiet

# IP: bd/block_design/ip/block_design_xlconcat_0_1/block_design_xlconcat_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==block_design_xlconcat_0_1 || ORIG_REF_NAME==block_design_xlconcat_0_1} -quiet] -quiet

# IP: bd/block_design/ip/block_design_axi_smc_6/block_design_axi_smc_6.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==block_design_axi_smc_6 || ORIG_REF_NAME==block_design_axi_smc_6} -quiet] -quiet

# Block Designs: c:/Users/ADMIN/Documents/ASCON-Vitis/ascon_test/ascon_test.gen/sources_1/bd/block_design/ip/block_design_axi_smc_6/bd_0/bd_b2e9.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/ADMIN/Documents/ASCON-Vitis/ascon_test/ascon_test.gen/sources_1/bd/block_design/ip/block_design_axi_smc_6/bd_0/ip/ip_0/bd_b2e9_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/ADMIN/Documents/ASCON-Vitis/ascon_test/ascon_test.gen/sources_1/bd/block_design/ip/block_design_axi_smc_6/bd_0/ip/ip_1/bd_b2e9_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/ADMIN/Documents/ASCON-Vitis/ascon_test/ascon_test.gen/sources_1/bd/block_design/ip/block_design_axi_smc_6/bd_0/ip/ip_2/bd_b2e9_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/ADMIN/Documents/ASCON-Vitis/ascon_test/ascon_test.gen/sources_1/bd/block_design/ip/block_design_axi_smc_6/bd_0/ip/ip_3/bd_b2e9_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/ADMIN/Documents/ASCON-Vitis/ascon_test/ascon_test.gen/sources_1/bd/block_design/ip/block_design_axi_smc_6/bd_0/ip/ip_4/bd_b2e9_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/ADMIN/Documents/ASCON-Vitis/ascon_test/ascon_test.gen/sources_1/bd/block_design/ip/block_design_axi_smc_6/bd_0/ip/ip_5/bd_b2e9_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/ADMIN/Documents/ASCON-Vitis/ascon_test/ascon_test.gen/sources_1/bd/block_design/ip/block_design_axi_smc_6/bd_0/ip/ip_6/bd_b2e9_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/ADMIN/Documents/ASCON-Vitis/ascon_test/ascon_test.gen/sources_1/bd/block_design/ip/block_design_axi_smc_6/bd_0/ip/ip_7/bd_b2e9_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/ADMIN/Documents/ASCON-Vitis/ascon_test/ascon_test.gen/sources_1/bd/block_design/ip/block_design_axi_smc_6/bd_0/ip/ip_8/bd_b2e9_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/ADMIN/Documents/ASCON-Vitis/ascon_test/ascon_test.gen/sources_1/bd/block_design/ip/block_design_axi_smc_6/bd_0/ip/ip_9/bd_b2e9_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/block_design/ip/block_design_axi_smc_1_0/block_design_axi_smc_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==block_design_axi_smc_1_0 || ORIG_REF_NAME==block_design_axi_smc_1_0} -quiet] -quiet

# Block Designs: c:/Users/ADMIN/Documents/ASCON-Vitis/ascon_test/ascon_test.gen/sources_1/bd/block_design/ip/block_design_axi_smc_1_0/bd_0/bd_c047.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/ADMIN/Documents/ASCON-Vitis/ascon_test/ascon_test.gen/sources_1/bd/block_design/ip/block_design_axi_smc_1_0/bd_0/ip/ip_0/bd_c047_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/ADMIN/Documents/ASCON-Vitis/ascon_test/ascon_test.gen/sources_1/bd/block_design/ip/block_design_axi_smc_1_0/bd_0/ip/ip_1/bd_c047_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/ADMIN/Documents/ASCON-Vitis/ascon_test/ascon_test.gen/sources_1/bd/block_design/ip/block_design_axi_smc_1_0/bd_0/ip/ip_2/bd_c047_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/ADMIN/Documents/ASCON-Vitis/ascon_test/ascon_test.gen/sources_1/bd/block_design/ip/block_design_axi_smc_1_0/bd_0/ip/ip_3/bd_c047_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/ADMIN/Documents/ASCON-Vitis/ascon_test/ascon_test.gen/sources_1/bd/block_design/ip/block_design_axi_smc_1_0/bd_0/ip/ip_4/bd_c047_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/ADMIN/Documents/ASCON-Vitis/ascon_test/ascon_test.gen/sources_1/bd/block_design/ip/block_design_axi_smc_1_0/bd_0/ip/ip_5/bd_c047_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/ADMIN/Documents/ASCON-Vitis/ascon_test/ascon_test.gen/sources_1/bd/block_design/ip/block_design_axi_smc_1_0/bd_0/ip/ip_6/bd_c047_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/ADMIN/Documents/ASCON-Vitis/ascon_test/ascon_test.gen/sources_1/bd/block_design/ip/block_design_axi_smc_1_0/bd_0/ip/ip_7/bd_c047_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/ADMIN/Documents/ASCON-Vitis/ascon_test/ascon_test.gen/sources_1/bd/block_design/ip/block_design_axi_smc_1_0/bd_0/ip/ip_8/bd_c047_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/ADMIN/Documents/ASCON-Vitis/ascon_test/ascon_test.gen/sources_1/bd/block_design/ip/block_design_axi_smc_1_0/bd_0/ip/ip_9/bd_c047_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/ADMIN/Documents/ASCON-Vitis/ascon_test/ascon_test.gen/sources_1/bd/block_design/ip/block_design_axi_smc_1_0/bd_0/ip/ip_10/bd_c047_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/block_design/ip/block_design_axi_dma_0_2/block_design_axi_dma_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==block_design_axi_dma_0_2 || ORIG_REF_NAME==block_design_axi_dma_0_2} -quiet] -quiet

# IP: bd/block_design/ip/block_design_ascon128_0_3/block_design_ascon128_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==block_design_ascon128_0_3 || ORIG_REF_NAME==block_design_ascon128_0_3} -quiet] -quiet

# IP: bd/block_design/ip/block_design_auto_ds_0/block_design_auto_ds_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==block_design_auto_ds_0 || ORIG_REF_NAME==block_design_auto_ds_0} -quiet] -quiet

# IP: bd/block_design/ip/block_design_auto_pc_0/block_design_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==block_design_auto_pc_0 || ORIG_REF_NAME==block_design_auto_pc_0} -quiet] -quiet

# IP: bd/block_design/ip/block_design_auto_ds_1/block_design_auto_ds_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==block_design_auto_ds_1 || ORIG_REF_NAME==block_design_auto_ds_1} -quiet] -quiet

# IP: bd/block_design/ip/block_design_auto_pc_1/block_design_auto_pc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==block_design_auto_pc_1 || ORIG_REF_NAME==block_design_auto_pc_1} -quiet] -quiet

# XDC: c:/Users/ADMIN/Documents/ASCON-Vitis/ascon_test/ascon_test.gen/sources_1/bd/block_design/ip/block_design_zynq_ultra_ps_e_0_2/block_design_zynq_ultra_ps_e_0_2_ooc.xdc

# XDC: c:/Users/ADMIN/Documents/ASCON-Vitis/ascon_test/ascon_test.gen/sources_1/bd/block_design/ip/block_design_zynq_ultra_ps_e_0_2/block_design_zynq_ultra_ps_e_0_2.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==block_design_zynq_ultra_ps_e_0_2 || ORIG_REF_NAME==block_design_zynq_ultra_ps_e_0_2} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/ADMIN/Documents/ASCON-Vitis/ascon_test/ascon_test.gen/sources_1/bd/block_design/ip/block_design_rst_ps8_0_100M_3/block_design_rst_ps8_0_100M_3_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==block_design_rst_ps8_0_100M_3 || ORIG_REF_NAME==block_design_rst_ps8_0_100M_3} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/ADMIN/Documents/ASCON-Vitis/ascon_test/ascon_test.gen/sources_1/bd/block_design/ip/block_design_rst_ps8_0_100M_3/block_design_rst_ps8_0_100M_3.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==block_design_rst_ps8_0_100M_3 || ORIG_REF_NAME==block_design_rst_ps8_0_100M_3} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/ADMIN/Documents/ASCON-Vitis/ascon_test/ascon_test.gen/sources_1/bd/block_design/ip/block_design_axi_smc_6/bd_0/ip/ip_1/bd_b2e9_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/ADMIN/Documents/ASCON-Vitis/ascon_test/ascon_test.gen/sources_1/bd/block_design/ip/block_design_axi_smc_6/bd_0/ip/ip_1/bd_b2e9_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/ADMIN/Documents/ASCON-Vitis/ascon_test/ascon_test.gen/sources_1/bd/block_design/ip/block_design_axi_smc_6/bd_0/ip/ip_5/bd_b2e9_s00a2s_0_ooc.xdc

# XDC: c:/Users/ADMIN/Documents/ASCON-Vitis/ascon_test/ascon_test.gen/sources_1/bd/block_design/ip/block_design_axi_smc_6/bd_0/ip/ip_6/bd_b2e9_sarn_0_ooc.xdc

# XDC: c:/Users/ADMIN/Documents/ASCON-Vitis/ascon_test/ascon_test.gen/sources_1/bd/block_design/ip/block_design_axi_smc_6/bd_0/ip/ip_6/bd_b2e9_sarn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/ADMIN/Documents/ASCON-Vitis/ascon_test/ascon_test.gen/sources_1/bd/block_design/ip/block_design_axi_smc_6/bd_0/ip/ip_7/bd_b2e9_srn_0_ooc.xdc

# XDC: c:/Users/ADMIN/Documents/ASCON-Vitis/ascon_test/ascon_test.gen/sources_1/bd/block_design/ip/block_design_axi_smc_6/bd_0/ip/ip_7/bd_b2e9_srn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/ADMIN/Documents/ASCON-Vitis/ascon_test/ascon_test.gen/sources_1/bd/block_design/ip/block_design_axi_smc_6/bd_0/ip/ip_8/bd_b2e9_m00s2a_0_ooc.xdc

# XDC: c:/Users/ADMIN/Documents/ASCON-Vitis/ascon_test/ascon_test.gen/sources_1/bd/block_design/ip/block_design_axi_smc_6/ooc.xdc

# XDC: c:/Users/ADMIN/Documents/ASCON-Vitis/ascon_test/ascon_test.gen/sources_1/bd/block_design/ip/block_design_axi_smc_6/smartconnect.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==block_design_axi_smc_6 || ORIG_REF_NAME==block_design_axi_smc_6} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/ADMIN/Documents/ASCON-Vitis/ascon_test/ascon_test.gen/sources_1/bd/block_design/ip/block_design_axi_smc_1_0/bd_0/ip/ip_1/bd_c047_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/ADMIN/Documents/ASCON-Vitis/ascon_test/ascon_test.gen/sources_1/bd/block_design/ip/block_design_axi_smc_1_0/bd_0/ip/ip_1/bd_c047_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/ADMIN/Documents/ASCON-Vitis/ascon_test/ascon_test.gen/sources_1/bd/block_design/ip/block_design_axi_smc_1_0/bd_0/ip/ip_5/bd_c047_s00a2s_0_ooc.xdc

# XDC: c:/Users/ADMIN/Documents/ASCON-Vitis/ascon_test/ascon_test.gen/sources_1/bd/block_design/ip/block_design_axi_smc_1_0/bd_0/ip/ip_6/bd_c047_sawn_0_ooc.xdc

# XDC: c:/Users/ADMIN/Documents/ASCON-Vitis/ascon_test/ascon_test.gen/sources_1/bd/block_design/ip/block_design_axi_smc_1_0/bd_0/ip/ip_6/bd_c047_sawn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/ADMIN/Documents/ASCON-Vitis/ascon_test/ascon_test.gen/sources_1/bd/block_design/ip/block_design_axi_smc_1_0/bd_0/ip/ip_7/bd_c047_swn_0_ooc.xdc

# XDC: c:/Users/ADMIN/Documents/ASCON-Vitis/ascon_test/ascon_test.gen/sources_1/bd/block_design/ip/block_design_axi_smc_1_0/bd_0/ip/ip_7/bd_c047_swn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/ADMIN/Documents/ASCON-Vitis/ascon_test/ascon_test.gen/sources_1/bd/block_design/ip/block_design_axi_smc_1_0/bd_0/ip/ip_8/bd_c047_sbn_0_ooc.xdc

# XDC: c:/Users/ADMIN/Documents/ASCON-Vitis/ascon_test/ascon_test.gen/sources_1/bd/block_design/ip/block_design_axi_smc_1_0/bd_0/ip/ip_8/bd_c047_sbn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/ADMIN/Documents/ASCON-Vitis/ascon_test/ascon_test.gen/sources_1/bd/block_design/ip/block_design_axi_smc_1_0/bd_0/ip/ip_9/bd_c047_m00s2a_0_ooc.xdc

# XDC: c:/Users/ADMIN/Documents/ASCON-Vitis/ascon_test/ascon_test.gen/sources_1/bd/block_design/ip/block_design_axi_smc_1_0/ooc.xdc

# XDC: c:/Users/ADMIN/Documents/ASCON-Vitis/ascon_test/ascon_test.gen/sources_1/bd/block_design/ip/block_design_axi_smc_1_0/smartconnect.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==block_design_axi_smc_1_0 || ORIG_REF_NAME==block_design_axi_smc_1_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/ADMIN/Documents/ASCON-Vitis/ascon_test/ascon_test.gen/sources_1/bd/block_design/ip/block_design_axi_dma_0_2/block_design_axi_dma_0_2.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==block_design_axi_dma_0_2 || ORIG_REF_NAME==block_design_axi_dma_0_2} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/ADMIN/Documents/ASCON-Vitis/ascon_test/ascon_test.gen/sources_1/bd/block_design/ip/block_design_axi_dma_0_2/block_design_axi_dma_0_2_clocks.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==block_design_axi_dma_0_2 || ORIG_REF_NAME==block_design_axi_dma_0_2} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/ADMIN/Documents/ASCON-Vitis/ascon_test/ascon_test.gen/sources_1/bd/block_design/ip/block_design_ascon128_0_3/constraints/ascon128_ooc.xdc

# XDC: c:/Users/ADMIN/Documents/ASCON-Vitis/ascon_test/ascon_test.gen/sources_1/bd/block_design/ip/block_design_auto_ds_0/block_design_auto_ds_0_clocks.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==block_design_auto_ds_0 || ORIG_REF_NAME==block_design_auto_ds_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/ADMIN/Documents/ASCON-Vitis/ascon_test/ascon_test.gen/sources_1/bd/block_design/ip/block_design_auto_ds_0/block_design_auto_ds_0_ooc.xdc

# XDC: c:/Users/ADMIN/Documents/ASCON-Vitis/ascon_test/ascon_test.gen/sources_1/bd/block_design/ip/block_design_auto_pc_0/block_design_auto_pc_0_ooc.xdc

# XDC: c:/Users/ADMIN/Documents/ASCON-Vitis/ascon_test/ascon_test.gen/sources_1/bd/block_design/ip/block_design_auto_ds_1/block_design_auto_ds_1_clocks.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==block_design_auto_ds_1 || ORIG_REF_NAME==block_design_auto_ds_1} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/ADMIN/Documents/ASCON-Vitis/ascon_test/ascon_test.gen/sources_1/bd/block_design/ip/block_design_auto_ds_1/block_design_auto_ds_1_ooc.xdc

# XDC: c:/Users/ADMIN/Documents/ASCON-Vitis/ascon_test/ascon_test.gen/sources_1/bd/block_design/ip/block_design_auto_pc_1/block_design_auto_pc_1_ooc.xdc

# XDC: c:/Users/ADMIN/Documents/ASCON-Vitis/ascon_test/ascon_test.gen/sources_1/bd/block_design/block_design_ooc.xdc
